name: CI

on:
  pull_request:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      MIX_ENV: test
      DATABASE_URL: postgres://postgres:postgres@postgres/event_store_test
    strategy:
      fail-fast: true
      matrix:
        adapter: [InMemory, Postgres]
        pub_sub: [Registry, Postgres]
        elixir: [1.12, 1.13, 1.14]
        otp: [22.x, 23.x, 24.x, 25.x]
        # https://hexdocs.pm/elixir/1.14.0/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
        exclude:
          - elixir: 1.12
            otp: 25.x
          - elixir: 1.14
            otp: 22.x

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get --only test
      - run: mix format --check-formatted
      - run: mix credo --all
      - run: mix do deps.get, deps.unlock --check-unused, deps.compile
      - run: mix ecto.setup
      - run: mix compile --warnings-as-errors
      - run: mix do compile --force, test --warnings-as-errors
        env:
          EVENT_STORE_ADAPTER: Elixir.EventStore.Adapters.${{matrix.adapter}}
          EVENT_STORE_PUB_SUB: Elixir.EventStore.PubSub.${{matrix.pub_sub}}
